### ISSUE TITLE
Renew the ratio of holdersShare

### ISSUE THREAD

**Issue by aggre** [dev-protocol/DIPs#1]
# Changing `holdersShare`

Now: [95%](https://github.com/dev-protocol/protocol/blob/master/docs/POLICY.md#holdersshare)
Propose: 51%

The ratio should be changed to prevent dumping of DEV and to enhance market entry by treating stakers loyal to the ecosystem more fairly.

> failing which market will be dumped hard by the Developers every morning after rewards are given out and staker will run and compete with the developer to dump with him ([quotes](https://discord.com/channels/547215761341546497/675499290940014604/716536535264133131))
> 5% stakers will be loyal not dumping the market..rest 95% are in greed including OSS Developers ([quotes](https://discord.com/channels/547215761341546497/675499290940014604/716536633507315772))

**Comment by mankal-2018** [comment]
Congrats to us!!

**Comment by aggre** [comment]
This proposal has been enabled with community voting. https://spectrum.chat/devtoken/general/lets-voting-dip1~9d980410-7f57-4562-99b6-1ac041b67d56
