### ISSUE TITLE
DIP #11- Stakes.Social UI/UX

### ISSUE THREAD

**Issue by defi-er** [dev-protocol/DIPs#11]
I would like to propose UI/UX upgrades for Stakes.social. 

**The Graph Dashboard**

The Dev Protocol team should look into thegraph.com. UniSwap uses the Graph for their dashboard, picture below.

![image](https://user-images.githubusercontent.com/64265685/88692024-9a118780-d0cb-11ea-88ea-7e2759761f2e.png)

The dashboard should show the following parameters:

1. DEV Staked
2. % of Supply Staked
3. Total Rewards Minted
4. Pools available
5. APY (Unless DIP #6 is adopted)
6. Rewards generated for Creators

**Categories and Trending**
This will give users more ways to find different properties

**Property and Creator Description**
Each Property should have a description, link to npmjs or Github, and info on creator(s) (optional). This will give users more info to make an educated decision on where to stake their tokens. 

**ENS Implementation** 
Allow assets on Dev Protocol  to be registered with an ENS address rather than a HEX address. This will improve UI/UX and security.

**Comment by defi-er** [comment]
+Open asset creators should be able to upload/write a roadmap on what they plan to achieve with the minted Dev tokens.

**Comment by aggre** [comment]
Already implemented
