### ISSUE TITLE
Identity Validation

### ISSUE THREAD

**Issue by aggre** [dev-protocol/DIPs#22]
This proposal conflicts with DIP #20 and should be compared and considered. The purpose of this proposal, as well as DIP #20, is to prevent self-staking. However, a softer approach is used to solve the problem.

I believe that these exclusive proposals should not be implemented in the first place. But if the problem is going to be too bloated, then we need to be considered for a healthful tokenomics.

The basic concept is to require a simple KYC for staking users and creators. (Conducted KYC can potentially be available for claiming identity for EIP 1812.)

The method of KYC uses a method that can identify a single identity with a high probability, like SMS authentication. Khaos is available for that KYC. With Khaos, personal information such as phone numbers can be authenticated while remaining confidential. Therefore, anonymity can be guaranteed.

The target users for requesting KYC is as follows:
- Property's shareholders
- Staking users

If a shareholder of a Property is attempting to stake on the Property, the KYC will verify that they are a different person. If they are the same person, the staking should be rejected.

## Advantages
With SMS authentication, it can prevent self-staking at a high rate. Unlike DIP #20, creators will still receive the benefits of the same support as before.

## Disadvantages
User experiences that require KYC, such as SMS authentication, are rare for on-chain protocols. Therefore, a friendly interface and an explanation of the need for it should be necessary.

**Comment by Akira-Taniguchi** [comment]
@aggre 
What about when two people conspire?
By Mr. A staking each other to Mr. B and Mr. B staking Mr. A.
You can create a situation similar to self-staking.

**Comment by aggre** [comment]
> @aggre
> What about when two people conspire?
> By Mr. A staking each other to Mr. B and Mr. B staking Mr. A.
> they can create a situation similar to self-staking.

This proposal does not prevent conspiracies on an off-chain. It would require DIP #20 to prevent it, but that presents too strong a constraint.

**Comment by aggre** [comment]
This method does not support the aggregation of staking by proxy contracts like the yearn strategy. And damages composability.
