### ISSUE TITLE
Standard Token Supply

### ISSUE THREAD

**Issue by defi-er** [dev-protocol/DIPs#30]
**Proposal**
I propose Dev Protocol to allow OSS projects to mint a standard 10,000,000 tokens. 

**Why**
This will help fix potential fragmentation and information asymetry. A standard supply will benefit Dev Protocol's ecosystem participants, especially when it comes to voting power, incentives, and ownership.

**Comment by aggre** [comment]
Property has a supply of 10 million tokens that cannot be mint or burned.

https://github.com/dev-protocol/protocol/blob/c6736b47089846a7004fd83aaeee653c04976995/contracts/src/property/Property.sol#L19-L20
