### ISSUE TITLE
Increase Creator Fee for Incubator Projects to 7.50%

### ISSUE THREAD

**Issue by defi-er** [dev-protocol/DIPs#49]
I am proposing to increase the Incubator Creator Fee to 7.50%, sent to the treasury, for Round 2 and all rounds after. The Incubator allows projects to earn up front rewards for joining the network. The additional 2.5% would help the treasury offset the inflation generated by the Incubator.

**Comment by aggre** [comment]
We can also apply this proposal to the first round, but is there any reason to target the next round?

**Comment by defi-er** [comment]
If it doesn't delay the launch then I'm okay with it being added now

**Comment by aggre** [comment]
We decided to adopt this proposal: https://discord.com/channels/547215761341546497/718353417973792777/815797861622611979
